baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "https://neavemj.github.io" # the base hostname & protocol for your site.
title: "Matthew J. Neave"

paginate: 10 #articles per page
paginate_path: /projects/page:num #makes pagination working

#contacts
git: "https://github.com/neavemj"  #your github url here.
stackoverflow: "" #Add your stackoverflow url here.
twitter: "https://twitter.com/MatthewNeave"  #Add your twitter url here.

#disqus comment
disqus:
    shortname: "Matt" #your disqus comment short name

#google analytics
google:
    tracking-id: "" #your tracking id here

gems:
  - jekyll-sitemap
  - jekyll-paginate

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "vendor"

permalink: /posts/:title

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
